# Reference: https://build-cpp.github.io/cmkr/cmake-toml
[project]
name = "regenny"

[vcpkg]
version = "2022.08.15"
packages = [
    "imgui[docking-experimental,freetype,sdl2-binding,opengl3-binding]",
    "fmt",
    "pegtl",
    "nativefiledialog",
    "spdlog",
    "utfcpp",
    "nlohmann-json",
    "glad[gl-api-30]",
    "lua",
    "sol2"
]

[fetch-content]
sdkgenny = { git = "https://github.com/cursey/sdkgenny.git", tag = "2bf398fdcc48346486b0e754a93da21fb788e245" }
luagenny = { git = "https://github.com/praydog/luagenny.git", tag = "5cdafd93b175a5aca92b5de935aa5c702a3b6ee7" }

[find-package]
imgui = {}
fmt = {}
pegtl = {}
unofficial-nativefiledialog = {}
spdlog = {}
utf8cpp = {}
SDL2 = {}
nlohmann_json = {}
glad = {}
sol2 = {}
lua = {}

[target.regenny]
type = "executable"
sources = [
    "src/**.cpp",
    "src/**.hpp",
    "thirdparty/**.cpp",
    "thirdparty/**.hpp",
    "thirdparty/**.h",
]
windows.sources = ["src/**.rc"]
include-directories = [
    "src/",
    "thirdparty/scope_gaurd/",
    "thirdparty/SDL_Trigger/",
]
link-libraries = [
    "imgui::imgui",
    "fmt::fmt",
    "taocpp::pegtl",
    "unofficial::nativefiledialog::nfd",
    "spdlog::spdlog",
    "utf8cpp",
    "SDL2::SDL2",
    "SDL2::SDL2main",
    "nlohmann_json::nlohmann_json",
    "glad::glad",
    "sdkgenny::sdkgenny",
    "lua",
    "sol2",
    "luagenny::luagenny",
]
compile-definitions = ["UTF_CPP_CPLUSPLUS=201103L"]
compile-features = ["cxx_std_17"]

[target.test0]
type = "executable"
sources = ["examples/test0.cpp"]
compile-features = ["cxx_std_17"]
